Repository pimcore/perspective-editor, pull requests merged in 2022-08, with the labels that each got.

#86 [Improvement]: Adapt docs for event listener
  doc/02_Customize_Menu_Entry_List.md
  src/PimcorePerspectiveEditorBundle.php
  src/Resources/public/js/pimcore/perspective/events.js
Labels: Improvement

#87 Setup unit tests and implement first 10 tests
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/config/config.yaml
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/packages/test/config.yaml
  .github/ci/files/config/routes/test/routes.yaml
  .github/ci/files/config/services.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/extensions.template.php
  .github/ci/files/kernel/Kernel.php
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/codeception.yml
  .gitignore
  codeception.dist.yml
  composer.json
  tests/Readme.md
  tests/Unit.suite.yml
  tests/Unit/PerspectiveAccessorTest.php
  tests/Unit/ViewAccessorTest.php
  tests/_bootstrap.php
  tests/_support/Helper/Unit.php
  tests/_support/UnitTester.php
  tests/bin/docker-compose.yml
  tests/bin/init-tests.sh
Labels: Task

#91 Task: Add js event compatibility for pimcore 11
  src/Resources/public/js/pimcore/perspective/events.js
Labels: Task

#89 Updated ramsey-composer version in codeception
  .github/workflows/codeception.yml
Labels: Bug

#93 [Task]: Remove Pimcore\Config\Config
  phpstan-baseline.neon
  phpstan.neon
  src/Services/PerspectiveAccessor.php
Labels: Task
