Repository pimcore/perspective-editor, pull requests merged in 2023-05, with the labels that each got.

#133 [Bug] Fixed unique check for tree items
  src/Controller/PerspectiveController.php
Labels: Bug

#135 [Task]: Update event listener in events.js
  src/Resources/public/js/pimcore/perspective/events.js
Labels: Task

#137 [Task] Pre Release Todo
  composer.json
Labels: Task

#139 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
Labels: sync
